TAP version 14
# Subtest: Authentication routes
    not ok 1 - fastify.ready is not a function
      ---
      stack: |
        Test.<anonymous> (test/auth.test.js:8:17)
      at:
        fileName: test/auth.test.js
        lineNumber: 8
        columnNumber: 17
        typeName: Test
        methodName: <anonymous>
        functionName: Test.<anonymous>
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |
        tap.test("Authentication routes", async (t) => {
          const fastify = buildFastify();
          await fastify.ready();
        ----------------^
      
          t.teardown(() => fastify.close());
      ...
    
    1..1
not ok 1 - Authentication routes # time=326.027ms
  ---
  at:
    fileName: test/auth.test.js
    lineNumber: 6
    columnNumber: 5
    typeName: Object
  source: |
    const supertest = require("supertest");
  
    tap.test("Authentication routes", async (t) => {
    ----^
      const fastify = buildFastify();
      await fastify.ready();
  ...

1..1
